nvis.shaders([
    "glsl/difference.json",
    "glsl/gaussian.json",
    "glsl/mixer.json",
    "glsl/pixelate.json",
    "glsl/sharpness.json",
    "glsl/sobel.json",
    "glsl/ssim.json",
    "glsl/tiling.json"
]);
nvis.graphs([
    "glsl/flip.json"
])